const destinations=[
{slug:'lumen',title:'Lumen',kicker:'North · Silence',day:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1800&q=88',night:'https://images.unsplash.com/photo-1483347756197-71ef80e95f73?auto=format&fit=crop&w=1800&q=88',alt:'Snow-covered mountain peaks',coordinates:'68.2097° N · 13.5034° E',summary:'A place where the horizon is almost monochrome and every ridge feels carved from light.',quote:'The silence here is not empty. It is architectural.',accent:'#e8bd69',rgb:'232,189,105',map:[18,28],facts:[['Season','Polar spring'],['Light','18 hours'],['Tempo','Still']],sound:'wind'},
{slug:'verdant',title:'Verdant',kicker:'West · Growth',day:'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1800&q=88',night:'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1800&q=88',alt:'Deep green forest',coordinates:'46.8797° N · 110.3626° W',summary:'A dense green chamber where sunlight arrives in fragments and the air feels newly invented.',quote:'Every path disappears just far enough to become an invitation.',accent:'#77d8a1',rgb:'119,216,161',map:[38,64],facts:[['Canopy','42 m'],['Humidity','81%'],['Sound','Rain']],sound:'rain'},
{slug:'ember',title:'Ember',kicker:'South · Heat',day:'https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=1800&q=88',night:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1800&q=88',alt:'Warm desert dunes',coordinates:'24.4539° N · 54.3773° E',summary:'Dunes hold the final light of day, turning distance into a slow gradient of copper and smoke.',quote:'The desert does not hide time. It stretches it.',accent:'#ff8d5c',rgb:'255,141,92',map:[66,72],facts:[['Surface','51°C'],['Wind','West'],['Hour','Golden']],sound:'hush'},
{slug:'tide',title:'Tide',kicker:'East · Motion',day:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1800&q=88',night:'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1800&q=88',alt:'Coastal cliffs and ocean',coordinates:'38.7223° N · 9.1393° W',summary:'A coastline shaped by repetition, where every wave redraws the border between land and sea.',quote:'Nothing stays still, yet the place remains unmistakably itself.',accent:'#77bfff',rgb:'119,191,255',map:[82,34],facts:[['Swell','2.4 m'],['Water','16°C'],['Rhythm','6 sec']],sound:'ocean'}
];
const $=s=>document.querySelector(s),root=document.documentElement,atlas=$('#atlas'),story=$('#story'),grid=$('#destinationGrid'),support=$('#supportNote');
let active=0,busy=false,isNight=false,motionOff=localStorage.getItem('elsewhere-motion')==='off',soundOn=false,audioCtx=null,audioNodes=[];
const pad=n=>String(n+1).padStart(2,'0');
function theme(p){root.style.setProperty('--accent',p.accent);root.style.setProperty('--accent-rgb',p.rgb);$('meta[name="theme-color"]').content=p.accent}
function cards(){grid.innerHTML=destinations.map((p,i)=>`<button class="destination-card" type="button" data-index="${i}" aria-label="Open ${p.title}"><span class="destination-card__media"><img class="destination-card__image" src="${p.day}" alt="${p.alt}" loading="${i?'lazy':'eager'}"></span><span class="destination-card__content"><span class="destination-card__index">${pad(i)}</span><span class="destination-card__title">${p.title}</span><span class="destination-card__meta"><span>${p.kicker}</span><span>Open ↗</span></span></span></button>`).join('')}
function map(){const m=$('#miniMap');m.innerHTML='<span class="map-line"></span>'+destinations.map((p,i)=>`<button class="map-point" style="left:${p.map[0]}%;top:${p.map[1]}%;--point:${p.accent}" data-index="${i}">${p.title}</button>`).join('')}
function timeline(){const t=$('#timeline');t.innerHTML=destinations.map((p,i)=>`<button class="timeline-dot ${i===active?'is-active':''}" data-index="${i}" aria-label="Open ${p.title}"></button>`).join('')}
function currentImage(p){return isNight?p.night:p.day}
function render(i){active=i;const p=destinations[i];theme(p);const img=currentImage(p);$('#storyImage').src=img;$('#storyImage').alt=p.alt;$('#storyTitle').textContent=p.title;$('#storyKicker').textContent=p.kicker;$('#storySummary').textContent=p.summary;$('#storyQuote').textContent=`“${p.quote}”`;$('#storyCoordinates').textContent=p.coordinates;$('#storyNumber').textContent=pad(i);$('#storyBackdrop').style.setProperty('--story-image',`url("${img}")`);$('#storyFacts').innerHTML=p.facts.map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('');$('#storyMode').textContent=isNight?'Night':'Day';$('#timeToggle').textContent=isNight?'Day view':'Night view';$('#timeToggle').ariaPressed=String(isNight);timeline();if(soundOn)startSound(p.sound)}
function view(show){atlas.classList.toggle('is-active',!show);atlas.toggleAttribute('aria-hidden',show);story.classList.toggle('is-active',show);story.toggleAttribute('aria-hidden',!show);scrollTo(0,0)}
function transition(update,done){if(busy)return;busy=true;const finish=()=>{busy=false;root.removeAttribute('data-direction');done?.()};if(!document.startViewTransition||motionOff||matchMedia('(prefers-reduced-motion: reduce)').matches){update();finish();return}document.startViewTransition(update).finished.then(finish,finish)}
function portalFrom(target){const r=target?.getBoundingClientRect();root.style.setProperty('--portal-x',`${r?r.left+r.width/2:innerWidth/2}px`);root.style.setProperty('--portal-y',`${r?r.top+r.height/2:innerHeight/2}px`)}
function openPlace(i,{push=true,target=null}={}){const card=grid.querySelector(`[data-index="${i}"]`);portalFrom(target||card);grid.querySelectorAll('.is-selected').forEach(x=>x.classList.remove('is-selected'));card?.classList.add('is-selected');render(i);transition(()=>view(true),()=>{$('#storyTitle').focus({preventScroll:true});card?.classList.remove('is-selected')});if(push)history.pushState({i},'',`#${destinations[i].slug}`)}
function closeStory({push=true}={}){const card=grid.querySelector(`[data-index="${active}"]`);portalFrom(card);card?.classList.add('is-selected');transition(()=>view(false),()=>{card?.focus({preventScroll:true});card?.classList.remove('is-selected')});if(push)history.pushState({},'',location.pathname+location.search)}
function move(dir,{push=true}={}){root.dataset.direction=dir>0?'next':'prev';const next=(active+dir+destinations.length)%destinations.length;transition(()=>render(next),()=>$('#storyTitle').focus({preventScroll:true}));if(push)history.pushState({i:next},'',`#${destinations[next].slug}`)}
function setMotion(){root.classList.toggle('no-motion',motionOff);$('#motionToggle').ariaPressed=String(motionOff);$('#motionToggle').textContent=`Motion: ${motionOff?'off':'on'}`;localStorage.setItem('elsewhere-motion',motionOff?'off':'on')}
function stopSound(){audioNodes.forEach(n=>{try{n.stop?.();n.disconnect?.()}catch{}});audioNodes=[]}
function startSound(type){stopSound();if(!soundOn)return;audioCtx ||= new AudioContext();const gain=audioCtx.createGain();gain.gain.value=.035;gain.connect(audioCtx.destination);const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*2,audioCtx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const src=audioCtx.createBufferSource();src.buffer=buffer;src.loop=true;const filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value={wind:420,rain:1500,hush:240,ocean:700}[type]||600;src.connect(filter).connect(gain);src.start();audioNodes=[src,filter,gain]}
function toggleSound(){soundOn=!soundOn;$('#soundToggle').ariaPressed=String(soundOn);$('#soundToggle').textContent=`Sound: ${soundOn?'on':'off'}`;soundOn?startSound(destinations[active].sound):stopSound()}
function setupCompare(){const options=destinations.map((p,i)=>`<option value="${i}">${p.title}</option>`).join('');$('#compareLeft').innerHTML=options;$('#compareRight').innerHTML=options;$('#compareRight').value='3';const draw=()=>{const a=destinations[+$('#compareLeft').value],b=destinations[+$('#compareRight').value];$('#compareImageA').src=a.day;$('#compareImageA').alt=a.alt;$('#compareImageB').src=b.day;$('#compareImageB').alt=b.alt};$('#compareLeft').onchange=draw;$('#compareRight').onchange=draw;$('#compareRange').oninput=e=>{const v=e.target.value;$('#compareLayer').style.width=`${v}%`;$('#compareHandle').style.left=`${v}%`};draw()}
function introDone(){const intro=$('#intro'),app=$('#app');transition(()=>{intro.classList.remove('is-active');app.hidden=false},()=>{grid.querySelector('button')?.focus({preventScroll:true});sessionStorage.setItem('elsewhere-intro','seen')})}
function cursor(){const c=$('#cursor');addEventListener('pointermove',e=>{c.style.left=`${e.clientX}px`;c.style.top=`${e.clientY}px`;c.classList.add('is-visible')});document.addEventListener('pointerover',e=>c.classList.toggle('is-active',!!e.target.closest('button,a,.destination-card,.map-point')))}
cards();map();setupCompare();cursor();setMotion();theme(destinations[0]);
$('#enterButton').onclick=$('#skipIntro').onclick=introDone;if(sessionStorage.getItem('elsewhere-intro')==='seen'){$('#intro').classList.remove('is-active');$('#app').hidden=false}
$('#motionToggle').onclick=()=>{motionOff=!motionOff;setMotion()};$('#soundToggle').onclick=toggleSound;$('#compareButton').onclick=()=>$('#compareDialog').showModal();
grid.onclick=e=>{const c=e.target.closest('.destination-card');if(c)openPlace(+c.dataset.index,{target:c})};$('#miniMap').onclick=e=>{const p=e.target.closest('.map-point');if(p)openPlace(+p.dataset.index,{target:p})};$('#timeline').onclick=e=>{const p=e.target.closest('.timeline-dot');if(p){root.dataset.direction=+p.dataset.index>active?'next':'prev';transition(()=>render(+p.dataset.index));history.pushState({i:+p.dataset.index},'',`#${destinations[+p.dataset.index].slug}`)}};
$('#backButton').onclick=()=>closeStory();$('#nextButton').onclick=$('#nextTextButton').onclick=()=>move(1);$('#previousButton').onclick=()=>move(-1);$('#timeToggle').onclick=()=>{isNight=!isNight;root.dataset.direction=isNight?'next':'prev';transition(()=>render(active))};
addEventListener('keydown',e=>{if(story.classList.contains('is-active')){if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1);if(e.key==='Escape')history.back()}else if(['ArrowRight','ArrowLeft'].includes(e.key)){const cs=[...grid.querySelectorAll('.destination-card')],current=Math.max(0,cs.indexOf(document.activeElement)),next=e.key==='ArrowRight'?(current+1)%cs.length:(current-1+cs.length)%cs.length;cs[next].focus()}});
let touchX=null;story.addEventListener('touchstart',e=>touchX=e.changedTouches[0].clientX,{passive:true});story.addEventListener('touchend',e=>{if(touchX===null)return;const d=e.changedTouches[0].clientX-touchX;if(Math.abs(d)>60)move(d<0?1:-1);touchX=null},{passive:true});
addEventListener('popstate',()=>{const slug=location.hash.slice(1),i=destinations.findIndex(p=>p.slug===slug);if(i>=0){story.classList.contains('is-active')?render(i):openPlace(i,{push:false})}else if(story.classList.contains('is-active'))closeStory({push:false})});
const initial=destinations.findIndex(p=>`#${p.slug}`===location.hash);if(initial>=0){$('#intro').classList.remove('is-active');$('#app').hidden=false;render(initial);view(true)}else history.replaceState({},'',location.pathname+location.search);
if(!document.startViewTransition){support.textContent='Accessible fallback active: this browser does not expose View Transitions.';support.classList.add('is-visible');setTimeout(()=>support.classList.remove('is-visible'),6500)}
